### ISSUE TITLE
包依赖问题

### ISSUE THREAD

**Issue by caicaicai** [xxd763795151/kafka-console-ui#1]
本地启动 找不到包 kafka.console.*下面的包

**Comment by xxd763795151** [comment]
是用idea启动还是，直接编译运行jar包了呀，如果是idea启动的话，注意配置下scala源码目录：

打开idea的Project Structure(Settings) -> Modules -> 设置src/main/scala为Sources，因为约定src/main/java是源码目录，所以这里要再加一个
打开idea的Project Structure(Settings) -> Libraries 添加scala sdk，然后选择本地下载的scala 2.13的目录，确定添加进来

**Comment by xxd763795151** [comment]
> 本地启动 找不到包 kafka.console.*下面的包

要是直接用maven直接打包启动的话，maven版本别低于3.6就行

**Comment by caicaicai** [comment]
我刚才发现了， 在scala包下面

**Comment by caicaicai** [comment]
为啥一半java，一半scala啊。。。好蛋疼

**Comment by xxd763795151** [comment]
> 为啥一半java，一半scala啊。。。好蛋疼
嗯，是有点畸形，我也感觉有点蛋疼了，最开始的时候，是我在研究kafka源码的时候，刚接触scala，然后找了几个开源的管理平台用着不趁手。就干脆自己搞个工具自己用，顺便用scala开发练下手，结果后来干脆就这样了。
