### ISSUE TITLE
使用SASL_PLAINTEXT认证，注意

### ISSUE THREAD

**Issue by immorwave** [xxd763795151/kafka-console-ui#10]
按照如下格式即可（直接修改用户名和密码后, 手动补充一个 \ 复制粘贴到集群属性）：

![企业微信截图_16457738736848](https://user-images.githubusercontent.com/25873871/155672704-bc5a9fe9-e5ac-4654-8a75-f7b8ec713fe4.png)

security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required\n这里后面补充一个 \\
username="user"\n这里后面补充一个\\
password="password";

**Comment by xxd763795151** [comment]
> 按照如下格式即可（直接修改用户名和密码后, 手动补充一个 \ 复制粘贴到集群属性）：
> 
> ![企业微信截图_16457738736848](https://user-images.githubusercontent.com/25873871/155672704-bc5a9fe9-e5ac-4654-8a75-f7b8ec713fe4.png)
> 
> security.protocol=SASL_PLAINTEXT sasl.mechanism=PLAIN sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required\n这里后面补充一个 \ username="user"\n这里后面补充一个\ password="password";

厉害，感谢。

补充一下：
```
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
# 不换行，可能长度不够，显示的时候自动换行，实际是一整行
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin!QAZ";

# 换行写法，直接回车换行，分3行写了，参照上面老哥提供的写法
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required\n\
username="admin" \n\
password="admin!QAZ";
```
<img width="989" alt="image" src="https://user-images.githubusercontent.com/19887530/155674200-fbebcea4-fbf4-4d0a-9fe3-b28f64ca7ee7.png">


另外在这里补充一下，sasl.jaas.config，使用的类，低版本的kafka用的：`org.apache.kafka.common.security.plain.PlainLoginModule`
但是这个版本用的是2.8.0的kafka客户端，类名已经改成：`org.apache.kafka.common.security.scram.ScramLoginModule` 了
