### ISSUE TITLE
如何使用docker-compose 进行部署

### ISSUE THREAD

**Issue by andyareyou** [xxd763795151/kafka-console-ui#12]
如何使用docker-compose 进行部署

**Comment by xxd763795151** [comment]
本打算最近提供docker镜像打包配置说明，这段时间没空一直没来得及搞。
这个工具本身是个普通java程序，不依赖外部任何服务的，可以直接打个docker镜像运行就可以启动的。docker-compose可以参考下常规单个服务吧，docker-compose我了解不多，目前提供不了太好的建议～～～

**Comment by xxd763795151** [comment]
hi，不知道这位小伙伴你们是否认识，人家分享了部署方式，如果有需要可以查看下：https://github.com/xxd763795151/kafka-console-ui/blob/main/document/deploy/docker%E9%83%A8%E7%BD%B2.md
