### ISSUE TITLE
实时消费 topic

### ISSUE THREAD

**Issue by hczs** [xxd763795151/kafka-console-ui#15]
您好！
很久之前 star 了项目，最近有时间体验了下功能，感觉非常棒！
有一个小问题，现在是否有选择 topic 然后启动一个消费者实时消费功能（就像在控制台那样）？

**Comment by xxd763795151** [comment]
> 您好！ 很久之前 star 了项目，最近有时间体验了下功能，感觉非常棒！ 有一个小问题，现在是否有选择 topic 然后启动一个消费者实时消费功能（就像在控制台那样）？

目前没有。不过，可以通重置消费偏移到最新的位点，或者查询发送的消息内容这两个配合起来能否满足。如果是想启动一个消费端在web实时显现目前消费到的消息，现在是不支持这个的。

**Comment by hczs** [comment]
> > 您好！ 很久之前 star 了项目，最近有时间体验了下功能，感觉非常棒！ 有一个小问题，现在是否有选择 topic 然后启动一个消费者实时消费功能（就像在控制台那样）？
> 
> 目前没有。不过，可以通重置消费偏移到最新的位点，或者查询发送的消息内容这两个配合起来能否满足。如果是想启动一个消费端在web实时显现目前消费到的消息，现在是不支持这个的。

好的，感谢！
