### ISSUE TITLE
如何修改context-path

### ISSUE THREAD

**Issue by leesonwei** [xxd763795151/kafka-console-ui#18]
我有注意到配置文件有寫不要修改context-path. 因為端口問題,需要修改context-path. 但是直接修改後無法訪問. 請問有什麼辦法可以修改context-path?

**Comment by xxd763795151** [comment]
> 

可能需要修改下前端这里的配置，重新打包，这个文件：https://github.com/xxd763795151/kafka-console-ui/blob/main/ui/.env
是这个配置项写死了：
`
VUE_APP_API_BASE_URL=/
`
因为在这个文件，创建axios实例的时候，用到这个配置：https://github.com/xxd763795151/kafka-console-ui/blob/main/ui/src/utils/request.js
```
const request = axios.create({
  // API 请求的默认前缀
  baseURL: process.env.VUE_APP_API_BASE_URL,
  timeout: 120000, // 请求超时时间
});

```
可以按需要修改重新打包， 打包步骤：https://github.com/xxd763795151/kafka-console-ui/blob/main/document/package/%E6%BA%90%E7%A0%81%E6%89%93%E5%8C%85.md

**Comment by leesonwei** [comment]
謝謝回復,我試下
