### ISSUE TITLE
如何用ACL進行模糊授權?

### ISSUE THREAD

**Issue by leesonwei** [xxd763795151/kafka-console-ui#19]
我有注意到在使用ACL的時候, 授權是填寫topic完整名稱的. 如果需要進行模糊授權比如某個用戶有寫入aa開頭的topic的權限,這樣的授權目前支持嗎?

**Comment by xxd763795151** [comment]
> 我有注意到在使用ACL的時候, 授權是填寫topic完整名稱的. 如果需要進行模糊授權比如某個用戶有寫入aa開頭的topic的權限,這樣的授權目前支持嗎?

目前不支持
