### ISSUE TITLE
希望能添加一个刷新按钮

### ISSUE THREAD

**Issue by Gszekt** [xxd763795151/kafka-console-ui#2]
消费组 | 消费详情 弹窗中希望能添加一个刷新按钮，方便观察实时信息

**Comment by xxd763795151** [comment]
> 消费组 | 消费详情 弹窗中希望能添加一个刷新按钮，方便观察实时信息

嗯，是，加个刷新，这样确实会方便一点

**Comment by xxd763795151** [comment]
嗯，这个刷新按钮已经加过了
