### ISSUE TITLE
docker  部署 还是连接127

### ISSUE THREAD

**Issue by andyareyou** [xxd763795151/kafka-console-ui#20]
![image](https://user-images.githubusercontent.com/50394654/222879254-a47f70a3-6f86-4273-90fa-ddee1999197a.png)

**Comment by xxd763795151** [comment]
> ![image](https://user-images.githubusercontent.com/50394654/222879254-a47f70a3-6f86-4273-90fa-ddee1999197a.png)

连接哪个集群，在集群切换里，默认应该是没有指定连接127的。需要自己增加一个集群配置的。
