### ISSUE TITLE
修改集群端口后不能正常工作，kafka-console-ui还是连接9092端口

### ISSUE THREAD

**Issue by ldcsaa** [xxd763795151/kafka-console-ui#23]
如图所示：

![image](https://github.com/xxd763795151/kafka-console-ui/assets/5990337/60ea2356-f116-4c85-91b9-4e0dfef8bd7b)

**Comment by xxd763795151** [comment]
在运维下面切换集群，没必要管这个默认配置
![image](https://github.com/xxd763795151/kafka-console-ui/assets/19887530/e6ce7704-c411-45e2-aa1d-3378f95d4b2f)

**Comment by xxd763795151** [comment]
运费菜单下面有集群切换，在这搞就行，这个配置文件其实不用管，主要是第一次启动的时候加载的默认配置，后面再启动之后都是在集群切换里管理了

**Comment by ldcsaa** [comment]
明白了。谢谢~~
