### ISSUE TITLE
ACL  SaslScram用户管理无法创建用户

### ISSUE THREAD

**Issue by qianyidui** [xxd763795151/kafka-console-ui#34]
![image](https://github.com/xxd763795151/kafka-console-ui/assets/18535866/8aec5e9b-87e8-43ca-9210-f07b98be0f27)

add user to kafka failed: org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support ALTER_USER_SCRAM_CREDENTIALS

**Comment by xxd763795151** [comment]
主页里有个详情，可以看到是否支持
![image](https://github.com/xxd763795151/kafka-console-ui/assets/19887530/bbb963b0-b0ff-4592-af76-6591c0a107fa)

这个是因为你的broker版本太低，还不支持这个API，应该是2.4版本之后才有。。。

解决办法只有两种：
1. 升级kafka版本，这个非常不现实
2. 采用命令行，或者找个其它类型管理台操作这个，业内应该有不少是支持的，他们这种对于低版本，可以直接操作zk实现

**Comment by qianyidui** [comment]
非常感谢，软件很棒！
