### ISSUE TITLE
无topic写权限却发送成功

### ISSUE THREAD

**Issue by qianyidui** [xxd763795151/kafka-console-ui#35]
使用消息发送，其实用户无topic写权限却提示发送成功  实则没有发送成功   应该把权限问题报出来

**Comment by xxd763795151** [comment]
嗯，之前默认是异步发送，最新的代码增加了选择同步或者异步，同步发送失败会返回错误信息 
![image](https://github.com/xxd763795151/kafka-console-ui/assets/19887530/1fe4ddde-bb5d-45ca-8e45-1243e43d7a06)

**Comment by xxd763795151** [comment]
已更新发布.
