### ISSUE TITLE
searchByTime  int maxNums = 5000;能否改为配置？

### ISSUE THREAD

**Issue by ppanphper** [xxd763795151/kafka-console-ui#36]
searchByTime  int maxNums = 5000;能否改为配置？

**Comment by xxd763795151** [comment]
> searchByTime int maxNums = 5000;能否改为配置？

![image](https://github.com/xxd763795151/kafka-console-ui/assets/19887530/7e03330a-e34e-4939-bf78-806100d71b1a)

改为可以配置的了.
