### ISSUE TITLE
更新配置时会使用更新前的缓存

### ISSUE THREAD

**Issue by ibarryyan** [xxd763795151/kafka-console-ui#39]
我把配置从A更新到B的Kafka地址，但是重启后仍然发现是Kafka A的相关topic信息，在删除data目录下的文件后再进行重启后恢复成当前配置正常的topic等信息，是否是缓存导致？

**Comment by xxd763795151** [comment]
管理台内置了数据库，正常情况下是在集群信息处，新增和删除集群信息，如下：
![image](https://github.com/xxd763795151/kafka-console-ui/assets/19887530/702c83c8-bcb4-44d1-8b24-1d1e00680722)

为了兼容最初配置文件的设计，所以初始化的时候会把配置文件里配置的集群信息（如果配置文件配置了集群信息），作为defautl增加到这个内置的数据库里。
可以在这个页面看到一个集群名称为default的集群。
如果不想要这个集群，直接在这个集群信息页面删除就好。

**Comment by ibarryyan** [comment]
> 管理台内置了数据库，正常情况下是在集群信息处，新增和删除集群信息，如下： ![image](https://private-user-images.githubusercontent.com/19887530/343591354-702c83c8-bcb4-44d1-8b24-1d1e00680722.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODMyNDcsIm5iZiI6MTcxOTQ4Mjk0NywicGF0aCI6Ii8xOTg4NzUzMC8zNDM1OTEzNTQtNzAyYzgzYzgtYmNiNC00NGQxLThiMjQtMWQxZTAwNjgwNzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEwMDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMDU0YTIyOGJiYzM0YWZmMzVmNDk2ZGQ3MzRhZDQwZTU3NTYxYmFkYWE1YmQ5NmFmZGMwNWUwMzczMjRmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W6obRTR5v4_MMkVYfFVtLCkQOW2N2k6m1Jikq992SnU)
> 
> 为了兼容最初配置文件的设计，所以初始化的时候会把配置文件里配置的集群信息（如果配置文件配置了集群信息），作为defautl增加到这个内置的数据库里。 可以在这个页面看到一个集群名称为default的集群。 如果不想要这个集群，直接在这个集群信息页面删除就好。

那如果临时增加topic那需要重启服务吗？

**Comment by xxd763795151** [comment]
> > 管理台内置了数据库，正常情况下是在集群信息处，新增和删除集群信息，如下： ![image](https://private-user-images.githubusercontent.com/19887530/343591354-702c83c8-bcb4-44d1-8b24-1d1e00680722.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODMyNDcsIm5iZiI6MTcxOTQ4Mjk0NywicGF0aCI6Ii8xOTg4NzUzMC8zNDM1OTEzNTQtNzAyYzgzYzgtYmNiNC00NGQxLThiMjQtMWQxZTAwNjgwNzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEwMDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMDU0YTIyOGJiYzM0YWZmMzVmNDk2ZGQ3MzRhZDQwZTU3NTYxYmFkYWE1YmQ5NmFmZGMwNWUwMzczMjRmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W6obRTR5v4_MMkVYfFVtLCkQOW2N2k6m1Jikq992SnU)
> > 为了兼容最初配置文件的设计，所以初始化的时候会把配置文件里配置的集群信息（如果配置文件配置了集群信息），作为defautl增加到这个内置的数据库里。 可以在这个页面看到一个集群名称为default的集群。 如果不想要这个集群，直接在这个集群信息页面删除就好。
> 
> 那如果临时增加topic那需要重启服务吗？
说的集群吧，topic肯定不需要。
在这地方增加集群不需要重启服务的，这个功能的目的就是在运行过程中增删集群，在右侧有个切换按钮，新增集群后点击切换，通过当前浏览器访问的时候，都是用的这个集群。也不影响别的使用者。
