### ISSUE TITLE
CheckBox未对齐

### ISSUE THREAD

**Issue by Gszekt** [xxd763795151/kafka-console-ui#4]
![图片](https://user-images.githubusercontent.com/26792853/145330407-da743190-3ecc-4c5f-884c-1ae4dc765341.png)

**Comment by xxd763795151** [comment]
> ![图片](https://user-images.githubusercontent.com/26792853/145330407-da743190-3ecc-4c5f-884c-1ae4dc765341.png)
噢噢，好的，我找个时间把它对齐一下，，，，，，

**Comment by xxd763795151** [comment]
> ![图片](https://user-images.githubusercontent.com/26792853/145330407-da743190-3ecc-4c5f-884c-1ae4dc765341.png)

呃，最新的代码已经对齐了，不用再调了~~~~
