### ISSUE TITLE
希望大佬添加topic中根据消息内容查询消息的功能

### ISSUE THREAD

**Issue by soulmate1314** [xxd763795151/kafka-console-ui#6]

**Comment by xxd763795151** [comment]
嗯，这个我随后考虑下怎么加合适，以前本来也想加的，后来没想好怎么加查询限制条件更合适点，就暂时没处理。因为这个涉及到消息体匹配，对查询性能肯定有影响，我想好加哪些限制条件了，就把这个加上。

**Comment by soulmate1314** [comment]
感觉平常用的已经很齐全了，就差消息查询这个了

**Comment by xxd763795151** [comment]
> 感觉平常用的已经很齐全了，就差消息查询这个了

已经加上了，根据时间查询的时候，支持根据消息头或者消息内容过滤。现在加了个多集群管理，和之前使用方式不太一样，把安装包下载下来，直接启动就行，启动后在页面配置集群地址，感兴趣的话可以看下文档说明：https://github.com/xxd763795151/kafka-console-ui
