### ISSUE TITLE
希望大佬能在搜索Topic的时候增加模糊匹配功能

### ISSUE THREAD

**Issue by ShenGuangYang** [xxd763795151/kafka-console-ui#7]
希望大佬能在搜索Topic的时候增加模糊匹配功能，如下图所示
![image](https://user-images.githubusercontent.com/18436796/147538925-7161f42d-132a-45e3-8562-73cab7abc183.png)

**Comment by xxd763795151** [comment]
> 希望大佬能在搜索Topic的时候增加模糊匹配功能，如下图所示 ![image](https://user-images.githubusercontent.com/18436796/147538925-7161f42d-132a-45e3-8562-73cab7abc183.png)

好的，昨天在用的时候就刚好也有这个想法

**Comment by xxd763795151** [comment]
> 希望大佬能在搜索Topic的时候增加模糊匹配功能，如下图所示 ![image](https://user-images.githubusercontent.com/18436796/147538925-7161f42d-132a-45e3-8562-73cab7abc183.png)

已经加上了topic的模糊匹配，增加了多集群管理，支持集群切换，感兴趣可以玩一下,看下最新的文档说明：https://github.com/xxd763795151/kafka-console-ui
