### ISSUE TITLE
希望大佬能在查询消息的时候支持时间降序筛选查询操作，目前默认是时间升序按时间段查询

### ISSUE THREAD

**Issue by xujin5038** [xxd763795151/kafka-console-ui#8]

**Comment by xxd763795151** [comment]
> _No description provided._

我大概明白你的意思。现在查询的时候是开始-结束时间范围内，最多5000条消息。从开始时间往后查。

如果 还是这5000条消息，是希望显示的时候可以调整时间降序展示还好弄。

但是如果是想从结束时间从后往前查，查5000条，这个确实不好弄。因为kafka写消息的时候是顺序写的，同时构建偏移索引和时间索引。kafka根据时间检索的时候，它这一块的本质实现就是拿时间索引计算出对应的偏移索引。
所以我查的时候也是这样，拿到消息偏移的时候，递增的方式往后检索。如果消息量大的话，也只检索5000条就返回了。

但是如果从后往前检索（从结束时间往前查），就很难计算这个数据量，可能某一秒量大，某一秒量小，需要一秒一秒从后往前来计算了。

**Comment by xujin5038** [comment]
谢谢大佬的细心回复，对，就是希望显示的时候可以调整时间降序展示，因为在实际使用时，查看数据是偏向于先看最新推送的数据

**Comment by xxd763795151** [comment]
好的，这个我回头找个时间加一下
