### ISSUE TITLE
web服务稳定性问题，其他人访问服务一直转圈圈

### ISSUE THREAD

**Issue by xujin5038** [xxd763795151/kafka-console-ui#9]
web服务稳定性问题，现象有:其他人访问服务一直转圈圈,自己访问只有一种浏览器正常，换其他浏览器也会转圈圈
![image](https://user-images.githubusercontent.com/42027915/149246987-d072b79a-f587-44fc-bd1a-034397a99244.png)

**Comment by xxd763795151** [comment]
可以看下浏览器控制台是否有报错，它的日志在部署的logs目录下。

**Comment by xujin5038** [comment]
应该是前端处理报错，需要对请求头中文编解码，报错相关信息如下https://www.cnblogs.com/guobin-/p/14014548.html

**Comment by xujin5038** [comment]
好的，谢谢大佬

**Comment by xxd763795151** [comment]
你可以先把集群名改成英文，比如：prod kafka,,,,,~~~~我平常 起名这样，习惯了。。。。结果没发现这个问题

**Comment by xxd763795151** [comment]
刚才处理了下，中文这个问题解决了下，消息查询展示的时候可以排序，降序显示了。还是原来那个安装包下载地址，需要的话重新下载下来就行 。解压开，只替换其中的jar包就行，本地配置的数据就还在。下载地址还是原来的地址：https://github.com/xxd763795151/kafka-console-ui/releases/download/v1.0.3/kafka-console-ui.zip

**Comment by xujin5038** [comment]
好的，辛苦大佬了

**Comment by xujin5038** [comment]
还有一个感觉可以完善的地方:看能不能支持默认全量数据查询，就是不用时间筛选的模式，有时候不想去限定具体时间，只关心某一个topic的全量数据按时间降序或升序，查看其数据情况

**Comment by xxd763795151** [comment]
> 还有一个感觉可以完善的地方:看能不能支持默认全量数据查询，就是不用时间筛选的模式，有时候不想去限定具体时间，只关心某一个topic的全量数据按时间降序或升序，查看其数据情况

这个肯定是不行的了，比如某些topic消息量大，每秒tps都上万，如果直接全量查询，可能会导致查询很久超时，或者是内存溢出。这个工具脚本里默认配置的堆内存是500M。

这个限制是必须加的，最多5000条，然后指定时间范围，就是想避免这种情况，而且我后台返回这个查询视图的时候，也是只返回一些元信息，都不保存消息体等信息，就也是担心有的消息体特别大，比如1M，查个几百条就内存炸了。

如果感觉消息量小的话，或者想看全部，可以把时间范围选长一点，比如从去年1号到当前时间。因为Kafka的消息有留存时间，有效时间可能就几天，查询时间范围大点就可以达到这个效果。

**Comment by xxd763795151** [comment]
其实呀，兄弟你是研发的话，如果你感觉你的场景可以针对性的调整的话，你可以把这个代码拉下来针对着去改，这代码实现也都比较简单，前台是VUE，后台是java，跟kafka交互这块用的scala，不过应该不涉及scala这块改造，直接调用接口就好。

这个项目用的是MIT协议，比apache license更自由，意思就是可以随便玩。

主要是，我弄的时候，有些地方想考虑通用性，就不太好针对性改。

**Comment by xujin5038** [comment]
可以，目前的功能其实够用了，我说的全量指的5000条查询结果
